# - Test for compiler support of std::result_of(lambda)

INCLUDE(CheckCXXSourceCompiles)

IF (CMAKE_COMPILER_IS_GNUCC)
    SET(CMAKE_REQUIRED_FLAGS "-std=c++0x -std=gnu++0x")
ENDIF(CMAKE_COMPILER_IS_GNUCC)

FILE(READ "${CMAKE_SOURCE_DIR}/cmake/TestForResultOfLambda.cpp" TESTFORRESULTOFLAMBDA_SRC)

CHECK_CXX_SOURCE_COMPILES("${TESTFORRESULTOFLAMBDA_SRC}" HAS_RESULTOF_LAMBDA)
